/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package xueqiao.quotation.admin.web.api.thriftapi;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class ReqCommodityActiveConfigOption implements org.apache.thrift.TBase<ReqCommodityActiveConfigOption, ReqCommodityActiveConfigOption._Fields>, java.io.Serializable, Cloneable, Comparable<ReqCommodityActiveConfigOption> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ReqCommodityActiveConfigOption");

  private static final org.apache.thrift.protocol.TField COMMODITY_NAME_PARTICAL_FIELD_DESC = new org.apache.thrift.protocol.TField("commodityNamePartical", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField COMMODITY_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("commodityId", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField ACTIVE_TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("activeType", org.apache.thrift.protocol.TType.I32, (short)3);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new ReqCommodityActiveConfigOptionStandardSchemeFactory());
    schemes.put(TupleScheme.class, new ReqCommodityActiveConfigOptionTupleSchemeFactory());
  }

  public String commodityNamePartical; // optional
  public int commodityId; // optional
  /**
   * 
   * @see xueqiao.quotation.account.thriftapi.ContractActiveType
   */
  public xueqiao.quotation.account.thriftapi.ContractActiveType activeType; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    COMMODITY_NAME_PARTICAL((short)1, "commodityNamePartical"),
    COMMODITY_ID((short)2, "commodityId"),
    /**
     * 
     * @see xueqiao.quotation.account.thriftapi.ContractActiveType
     */
    ACTIVE_TYPE((short)3, "activeType");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // COMMODITY_NAME_PARTICAL
          return COMMODITY_NAME_PARTICAL;
        case 2: // COMMODITY_ID
          return COMMODITY_ID;
        case 3: // ACTIVE_TYPE
          return ACTIVE_TYPE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __COMMODITYID_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  private _Fields optionals[] = {_Fields.COMMODITY_NAME_PARTICAL,_Fields.COMMODITY_ID,_Fields.ACTIVE_TYPE};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.COMMODITY_NAME_PARTICAL, new org.apache.thrift.meta_data.FieldMetaData("commodityNamePartical", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.COMMODITY_ID, new org.apache.thrift.meta_data.FieldMetaData("commodityId", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.ACTIVE_TYPE, new org.apache.thrift.meta_data.FieldMetaData("activeType", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, xueqiao.quotation.account.thriftapi.ContractActiveType.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ReqCommodityActiveConfigOption.class, metaDataMap);
  }

  public ReqCommodityActiveConfigOption() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ReqCommodityActiveConfigOption(ReqCommodityActiveConfigOption other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetCommodityNamePartical()) {
      this.commodityNamePartical = other.commodityNamePartical;
    }
    this.commodityId = other.commodityId;
    if (other.isSetActiveType()) {
      this.activeType = other.activeType;
    }
  }

  public ReqCommodityActiveConfigOption deepCopy() {
    return new ReqCommodityActiveConfigOption(this);
  }

  @Override
  public void clear() {
    this.commodityNamePartical = null;
    setCommodityIdIsSet(false);
    this.commodityId = 0;
    this.activeType = null;
  }

  public String getCommodityNamePartical() {
    return this.commodityNamePartical;
  }

  public ReqCommodityActiveConfigOption setCommodityNamePartical(String commodityNamePartical) {
    this.commodityNamePartical = commodityNamePartical;
    return this;
  }

  public void unsetCommodityNamePartical() {
    this.commodityNamePartical = null;
  }

  /** Returns true if field commodityNamePartical is set (has been assigned a value) and false otherwise */
  public boolean isSetCommodityNamePartical() {
    return this.commodityNamePartical != null;
  }

  public void setCommodityNameParticalIsSet(boolean value) {
    if (!value) {
      this.commodityNamePartical = null;
    }
  }

  public int getCommodityId() {
    return this.commodityId;
  }

  public ReqCommodityActiveConfigOption setCommodityId(int commodityId) {
    this.commodityId = commodityId;
    setCommodityIdIsSet(true);
    return this;
  }

  public void unsetCommodityId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __COMMODITYID_ISSET_ID);
  }

  /** Returns true if field commodityId is set (has been assigned a value) and false otherwise */
  public boolean isSetCommodityId() {
    return EncodingUtils.testBit(__isset_bitfield, __COMMODITYID_ISSET_ID);
  }

  public void setCommodityIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __COMMODITYID_ISSET_ID, value);
  }

  /**
   * 
   * @see xueqiao.quotation.account.thriftapi.ContractActiveType
   */
  public xueqiao.quotation.account.thriftapi.ContractActiveType getActiveType() {
    return this.activeType;
  }

  /**
   * 
   * @see xueqiao.quotation.account.thriftapi.ContractActiveType
   */
  public ReqCommodityActiveConfigOption setActiveType(xueqiao.quotation.account.thriftapi.ContractActiveType activeType) {
    this.activeType = activeType;
    return this;
  }

  public void unsetActiveType() {
    this.activeType = null;
  }

  /** Returns true if field activeType is set (has been assigned a value) and false otherwise */
  public boolean isSetActiveType() {
    return this.activeType != null;
  }

  public void setActiveTypeIsSet(boolean value) {
    if (!value) {
      this.activeType = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case COMMODITY_NAME_PARTICAL:
      if (value == null) {
        unsetCommodityNamePartical();
      } else {
        setCommodityNamePartical((String)value);
      }
      break;

    case COMMODITY_ID:
      if (value == null) {
        unsetCommodityId();
      } else {
        setCommodityId((Integer)value);
      }
      break;

    case ACTIVE_TYPE:
      if (value == null) {
        unsetActiveType();
      } else {
        setActiveType((xueqiao.quotation.account.thriftapi.ContractActiveType)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case COMMODITY_NAME_PARTICAL:
      return getCommodityNamePartical();

    case COMMODITY_ID:
      return Integer.valueOf(getCommodityId());

    case ACTIVE_TYPE:
      return getActiveType();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case COMMODITY_NAME_PARTICAL:
      return isSetCommodityNamePartical();
    case COMMODITY_ID:
      return isSetCommodityId();
    case ACTIVE_TYPE:
      return isSetActiveType();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof ReqCommodityActiveConfigOption)
      return this.equals((ReqCommodityActiveConfigOption)that);
    return false;
  }

  public boolean equals(ReqCommodityActiveConfigOption that) {
    if (that == null)
      return false;

    boolean this_present_commodityNamePartical = true && this.isSetCommodityNamePartical();
    boolean that_present_commodityNamePartical = true && that.isSetCommodityNamePartical();
    if (this_present_commodityNamePartical || that_present_commodityNamePartical) {
      if (!(this_present_commodityNamePartical && that_present_commodityNamePartical))
        return false;
      if (!this.commodityNamePartical.equals(that.commodityNamePartical))
        return false;
    }

    boolean this_present_commodityId = true && this.isSetCommodityId();
    boolean that_present_commodityId = true && that.isSetCommodityId();
    if (this_present_commodityId || that_present_commodityId) {
      if (!(this_present_commodityId && that_present_commodityId))
        return false;
      if (this.commodityId != that.commodityId)
        return false;
    }

    boolean this_present_activeType = true && this.isSetActiveType();
    boolean that_present_activeType = true && that.isSetActiveType();
    if (this_present_activeType || that_present_activeType) {
      if (!(this_present_activeType && that_present_activeType))
        return false;
      if (!this.activeType.equals(that.activeType))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(ReqCommodityActiveConfigOption other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetCommodityNamePartical()).compareTo(other.isSetCommodityNamePartical());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCommodityNamePartical()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.commodityNamePartical, other.commodityNamePartical);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCommodityId()).compareTo(other.isSetCommodityId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCommodityId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.commodityId, other.commodityId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetActiveType()).compareTo(other.isSetActiveType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetActiveType()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.activeType, other.activeType);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("ReqCommodityActiveConfigOption(");
    boolean first = true;

    if (isSetCommodityNamePartical()) {
      sb.append("commodityNamePartical:");
      if (this.commodityNamePartical == null) {
        sb.append("null");
      } else {
        sb.append(this.commodityNamePartical);
      }
      first = false;
    }
    if (isSetCommodityId()) {
      if (!first) sb.append(", ");
      sb.append("commodityId:");
      sb.append(this.commodityId);
      first = false;
    }
    if (isSetActiveType()) {
      if (!first) sb.append(", ");
      sb.append("activeType:");
      if (this.activeType == null) {
        sb.append("null");
      } else {
        sb.append(this.activeType);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ReqCommodityActiveConfigOptionStandardSchemeFactory implements SchemeFactory {
    public ReqCommodityActiveConfigOptionStandardScheme getScheme() {
      return new ReqCommodityActiveConfigOptionStandardScheme();
    }
  }

  private static class ReqCommodityActiveConfigOptionStandardScheme extends StandardScheme<ReqCommodityActiveConfigOption> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ReqCommodityActiveConfigOption struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // COMMODITY_NAME_PARTICAL
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.commodityNamePartical = iprot.readString();
              struct.setCommodityNameParticalIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // COMMODITY_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.commodityId = iprot.readI32();
              struct.setCommodityIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // ACTIVE_TYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.activeType = xueqiao.quotation.account.thriftapi.ContractActiveType.findByValue(iprot.readI32());
              struct.setActiveTypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ReqCommodityActiveConfigOption struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.commodityNamePartical != null) {
        if (struct.isSetCommodityNamePartical()) {
          oprot.writeFieldBegin(COMMODITY_NAME_PARTICAL_FIELD_DESC);
          oprot.writeString(struct.commodityNamePartical);
          oprot.writeFieldEnd();
        }
      }
      if (struct.isSetCommodityId()) {
        oprot.writeFieldBegin(COMMODITY_ID_FIELD_DESC);
        oprot.writeI32(struct.commodityId);
        oprot.writeFieldEnd();
      }
      if (struct.activeType != null) {
        if (struct.isSetActiveType()) {
          oprot.writeFieldBegin(ACTIVE_TYPE_FIELD_DESC);
          oprot.writeI32(struct.activeType.getValue());
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ReqCommodityActiveConfigOptionTupleSchemeFactory implements SchemeFactory {
    public ReqCommodityActiveConfigOptionTupleScheme getScheme() {
      return new ReqCommodityActiveConfigOptionTupleScheme();
    }
  }

  private static class ReqCommodityActiveConfigOptionTupleScheme extends TupleScheme<ReqCommodityActiveConfigOption> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ReqCommodityActiveConfigOption struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetCommodityNamePartical()) {
        optionals.set(0);
      }
      if (struct.isSetCommodityId()) {
        optionals.set(1);
      }
      if (struct.isSetActiveType()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetCommodityNamePartical()) {
        oprot.writeString(struct.commodityNamePartical);
      }
      if (struct.isSetCommodityId()) {
        oprot.writeI32(struct.commodityId);
      }
      if (struct.isSetActiveType()) {
        oprot.writeI32(struct.activeType.getValue());
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ReqCommodityActiveConfigOption struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.commodityNamePartical = iprot.readString();
        struct.setCommodityNameParticalIsSet(true);
      }
      if (incoming.get(1)) {
        struct.commodityId = iprot.readI32();
        struct.setCommodityIdIsSet(true);
      }
      if (incoming.get(2)) {
        struct.activeType = xueqiao.quotation.account.thriftapi.ContractActiveType.findByValue(iprot.readI32());
        struct.setActiveTypeIsSet(true);
      }
    }
  }

}

