/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.longsheng.xueqiao.broker.thriftapi;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class ReqBrokerOption implements org.apache.thrift.TBase<ReqBrokerOption, ReqBrokerOption._Fields>, java.io.Serializable, Cloneable, Comparable<ReqBrokerOption> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ReqBrokerOption");

  private static final org.apache.thrift.protocol.TField BROKER_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("brokerId", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField ENG_NAME_WHOLE_FIELD_DESC = new org.apache.thrift.protocol.TField("engNameWhole", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField ENG_NAME_PARTICAL_FIELD_DESC = new org.apache.thrift.protocol.TField("engNamePartical", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField CN_NAME_WHOLE_FIELD_DESC = new org.apache.thrift.protocol.TField("cnNameWhole", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField CN_NAME_PARTICAL_FIELD_DESC = new org.apache.thrift.protocol.TField("cnNamePartical", org.apache.thrift.protocol.TType.STRING, (short)5);
  private static final org.apache.thrift.protocol.TField ENV_FIELD_DESC = new org.apache.thrift.protocol.TField("env", org.apache.thrift.protocol.TType.I32, (short)6);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new ReqBrokerOptionStandardSchemeFactory());
    schemes.put(TupleScheme.class, new ReqBrokerOptionTupleSchemeFactory());
  }

  public int brokerId; // optional
  public String engNameWhole; // optional
  public String engNamePartical; // optional
  public String cnNameWhole; // optional
  public String cnNamePartical; // optional
  /**
   * 
   * @see com.longsheng.xueqiao.broker.thriftapi.TechPlatformEnv
   */
  public com.longsheng.xueqiao.broker.thriftapi.TechPlatformEnv env; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    BROKER_ID((short)1, "brokerId"),
    ENG_NAME_WHOLE((short)2, "engNameWhole"),
    ENG_NAME_PARTICAL((short)3, "engNamePartical"),
    CN_NAME_WHOLE((short)4, "cnNameWhole"),
    CN_NAME_PARTICAL((short)5, "cnNamePartical"),
    /**
     * 
     * @see com.longsheng.xueqiao.broker.thriftapi.TechPlatformEnv
     */
    ENV((short)6, "env");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // BROKER_ID
          return BROKER_ID;
        case 2: // ENG_NAME_WHOLE
          return ENG_NAME_WHOLE;
        case 3: // ENG_NAME_PARTICAL
          return ENG_NAME_PARTICAL;
        case 4: // CN_NAME_WHOLE
          return CN_NAME_WHOLE;
        case 5: // CN_NAME_PARTICAL
          return CN_NAME_PARTICAL;
        case 6: // ENV
          return ENV;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __BROKERID_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  private _Fields optionals[] = {_Fields.BROKER_ID,_Fields.ENG_NAME_WHOLE,_Fields.ENG_NAME_PARTICAL,_Fields.CN_NAME_WHOLE,_Fields.CN_NAME_PARTICAL,_Fields.ENV};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.BROKER_ID, new org.apache.thrift.meta_data.FieldMetaData("brokerId", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.ENG_NAME_WHOLE, new org.apache.thrift.meta_data.FieldMetaData("engNameWhole", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.ENG_NAME_PARTICAL, new org.apache.thrift.meta_data.FieldMetaData("engNamePartical", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.CN_NAME_WHOLE, new org.apache.thrift.meta_data.FieldMetaData("cnNameWhole", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.CN_NAME_PARTICAL, new org.apache.thrift.meta_data.FieldMetaData("cnNamePartical", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.ENV, new org.apache.thrift.meta_data.FieldMetaData("env", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, com.longsheng.xueqiao.broker.thriftapi.TechPlatformEnv.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ReqBrokerOption.class, metaDataMap);
  }

  public ReqBrokerOption() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ReqBrokerOption(ReqBrokerOption other) {
    __isset_bitfield = other.__isset_bitfield;
    this.brokerId = other.brokerId;
    if (other.isSetEngNameWhole()) {
      this.engNameWhole = other.engNameWhole;
    }
    if (other.isSetEngNamePartical()) {
      this.engNamePartical = other.engNamePartical;
    }
    if (other.isSetCnNameWhole()) {
      this.cnNameWhole = other.cnNameWhole;
    }
    if (other.isSetCnNamePartical()) {
      this.cnNamePartical = other.cnNamePartical;
    }
    if (other.isSetEnv()) {
      this.env = other.env;
    }
  }

  public ReqBrokerOption deepCopy() {
    return new ReqBrokerOption(this);
  }

  @Override
  public void clear() {
    setBrokerIdIsSet(false);
    this.brokerId = 0;
    this.engNameWhole = null;
    this.engNamePartical = null;
    this.cnNameWhole = null;
    this.cnNamePartical = null;
    this.env = null;
  }

  public int getBrokerId() {
    return this.brokerId;
  }

  public ReqBrokerOption setBrokerId(int brokerId) {
    this.brokerId = brokerId;
    setBrokerIdIsSet(true);
    return this;
  }

  public void unsetBrokerId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __BROKERID_ISSET_ID);
  }

  /** Returns true if field brokerId is set (has been assigned a value) and false otherwise */
  public boolean isSetBrokerId() {
    return EncodingUtils.testBit(__isset_bitfield, __BROKERID_ISSET_ID);
  }

  public void setBrokerIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __BROKERID_ISSET_ID, value);
  }

  public String getEngNameWhole() {
    return this.engNameWhole;
  }

  public ReqBrokerOption setEngNameWhole(String engNameWhole) {
    this.engNameWhole = engNameWhole;
    return this;
  }

  public void unsetEngNameWhole() {
    this.engNameWhole = null;
  }

  /** Returns true if field engNameWhole is set (has been assigned a value) and false otherwise */
  public boolean isSetEngNameWhole() {
    return this.engNameWhole != null;
  }

  public void setEngNameWholeIsSet(boolean value) {
    if (!value) {
      this.engNameWhole = null;
    }
  }

  public String getEngNamePartical() {
    return this.engNamePartical;
  }

  public ReqBrokerOption setEngNamePartical(String engNamePartical) {
    this.engNamePartical = engNamePartical;
    return this;
  }

  public void unsetEngNamePartical() {
    this.engNamePartical = null;
  }

  /** Returns true if field engNamePartical is set (has been assigned a value) and false otherwise */
  public boolean isSetEngNamePartical() {
    return this.engNamePartical != null;
  }

  public void setEngNameParticalIsSet(boolean value) {
    if (!value) {
      this.engNamePartical = null;
    }
  }

  public String getCnNameWhole() {
    return this.cnNameWhole;
  }

  public ReqBrokerOption setCnNameWhole(String cnNameWhole) {
    this.cnNameWhole = cnNameWhole;
    return this;
  }

  public void unsetCnNameWhole() {
    this.cnNameWhole = null;
  }

  /** Returns true if field cnNameWhole is set (has been assigned a value) and false otherwise */
  public boolean isSetCnNameWhole() {
    return this.cnNameWhole != null;
  }

  public void setCnNameWholeIsSet(boolean value) {
    if (!value) {
      this.cnNameWhole = null;
    }
  }

  public String getCnNamePartical() {
    return this.cnNamePartical;
  }

  public ReqBrokerOption setCnNamePartical(String cnNamePartical) {
    this.cnNamePartical = cnNamePartical;
    return this;
  }

  public void unsetCnNamePartical() {
    this.cnNamePartical = null;
  }

  /** Returns true if field cnNamePartical is set (has been assigned a value) and false otherwise */
  public boolean isSetCnNamePartical() {
    return this.cnNamePartical != null;
  }

  public void setCnNameParticalIsSet(boolean value) {
    if (!value) {
      this.cnNamePartical = null;
    }
  }

  /**
   * 
   * @see com.longsheng.xueqiao.broker.thriftapi.TechPlatformEnv
   */
  public com.longsheng.xueqiao.broker.thriftapi.TechPlatformEnv getEnv() {
    return this.env;
  }

  /**
   * 
   * @see com.longsheng.xueqiao.broker.thriftapi.TechPlatformEnv
   */
  public ReqBrokerOption setEnv(com.longsheng.xueqiao.broker.thriftapi.TechPlatformEnv env) {
    this.env = env;
    return this;
  }

  public void unsetEnv() {
    this.env = null;
  }

  /** Returns true if field env is set (has been assigned a value) and false otherwise */
  public boolean isSetEnv() {
    return this.env != null;
  }

  public void setEnvIsSet(boolean value) {
    if (!value) {
      this.env = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case BROKER_ID:
      if (value == null) {
        unsetBrokerId();
      } else {
        setBrokerId((Integer)value);
      }
      break;

    case ENG_NAME_WHOLE:
      if (value == null) {
        unsetEngNameWhole();
      } else {
        setEngNameWhole((String)value);
      }
      break;

    case ENG_NAME_PARTICAL:
      if (value == null) {
        unsetEngNamePartical();
      } else {
        setEngNamePartical((String)value);
      }
      break;

    case CN_NAME_WHOLE:
      if (value == null) {
        unsetCnNameWhole();
      } else {
        setCnNameWhole((String)value);
      }
      break;

    case CN_NAME_PARTICAL:
      if (value == null) {
        unsetCnNamePartical();
      } else {
        setCnNamePartical((String)value);
      }
      break;

    case ENV:
      if (value == null) {
        unsetEnv();
      } else {
        setEnv((com.longsheng.xueqiao.broker.thriftapi.TechPlatformEnv)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case BROKER_ID:
      return Integer.valueOf(getBrokerId());

    case ENG_NAME_WHOLE:
      return getEngNameWhole();

    case ENG_NAME_PARTICAL:
      return getEngNamePartical();

    case CN_NAME_WHOLE:
      return getCnNameWhole();

    case CN_NAME_PARTICAL:
      return getCnNamePartical();

    case ENV:
      return getEnv();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case BROKER_ID:
      return isSetBrokerId();
    case ENG_NAME_WHOLE:
      return isSetEngNameWhole();
    case ENG_NAME_PARTICAL:
      return isSetEngNamePartical();
    case CN_NAME_WHOLE:
      return isSetCnNameWhole();
    case CN_NAME_PARTICAL:
      return isSetCnNamePartical();
    case ENV:
      return isSetEnv();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof ReqBrokerOption)
      return this.equals((ReqBrokerOption)that);
    return false;
  }

  public boolean equals(ReqBrokerOption that) {
    if (that == null)
      return false;

    boolean this_present_brokerId = true && this.isSetBrokerId();
    boolean that_present_brokerId = true && that.isSetBrokerId();
    if (this_present_brokerId || that_present_brokerId) {
      if (!(this_present_brokerId && that_present_brokerId))
        return false;
      if (this.brokerId != that.brokerId)
        return false;
    }

    boolean this_present_engNameWhole = true && this.isSetEngNameWhole();
    boolean that_present_engNameWhole = true && that.isSetEngNameWhole();
    if (this_present_engNameWhole || that_present_engNameWhole) {
      if (!(this_present_engNameWhole && that_present_engNameWhole))
        return false;
      if (!this.engNameWhole.equals(that.engNameWhole))
        return false;
    }

    boolean this_present_engNamePartical = true && this.isSetEngNamePartical();
    boolean that_present_engNamePartical = true && that.isSetEngNamePartical();
    if (this_present_engNamePartical || that_present_engNamePartical) {
      if (!(this_present_engNamePartical && that_present_engNamePartical))
        return false;
      if (!this.engNamePartical.equals(that.engNamePartical))
        return false;
    }

    boolean this_present_cnNameWhole = true && this.isSetCnNameWhole();
    boolean that_present_cnNameWhole = true && that.isSetCnNameWhole();
    if (this_present_cnNameWhole || that_present_cnNameWhole) {
      if (!(this_present_cnNameWhole && that_present_cnNameWhole))
        return false;
      if (!this.cnNameWhole.equals(that.cnNameWhole))
        return false;
    }

    boolean this_present_cnNamePartical = true && this.isSetCnNamePartical();
    boolean that_present_cnNamePartical = true && that.isSetCnNamePartical();
    if (this_present_cnNamePartical || that_present_cnNamePartical) {
      if (!(this_present_cnNamePartical && that_present_cnNamePartical))
        return false;
      if (!this.cnNamePartical.equals(that.cnNamePartical))
        return false;
    }

    boolean this_present_env = true && this.isSetEnv();
    boolean that_present_env = true && that.isSetEnv();
    if (this_present_env || that_present_env) {
      if (!(this_present_env && that_present_env))
        return false;
      if (!this.env.equals(that.env))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(ReqBrokerOption other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetBrokerId()).compareTo(other.isSetBrokerId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBrokerId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.brokerId, other.brokerId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetEngNameWhole()).compareTo(other.isSetEngNameWhole());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEngNameWhole()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.engNameWhole, other.engNameWhole);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetEngNamePartical()).compareTo(other.isSetEngNamePartical());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEngNamePartical()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.engNamePartical, other.engNamePartical);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCnNameWhole()).compareTo(other.isSetCnNameWhole());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCnNameWhole()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.cnNameWhole, other.cnNameWhole);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCnNamePartical()).compareTo(other.isSetCnNamePartical());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCnNamePartical()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.cnNamePartical, other.cnNamePartical);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetEnv()).compareTo(other.isSetEnv());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEnv()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.env, other.env);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("ReqBrokerOption(");
    boolean first = true;

    if (isSetBrokerId()) {
      sb.append("brokerId:");
      sb.append(this.brokerId);
      first = false;
    }
    if (isSetEngNameWhole()) {
      if (!first) sb.append(", ");
      sb.append("engNameWhole:");
      if (this.engNameWhole == null) {
        sb.append("null");
      } else {
        sb.append(this.engNameWhole);
      }
      first = false;
    }
    if (isSetEngNamePartical()) {
      if (!first) sb.append(", ");
      sb.append("engNamePartical:");
      if (this.engNamePartical == null) {
        sb.append("null");
      } else {
        sb.append(this.engNamePartical);
      }
      first = false;
    }
    if (isSetCnNameWhole()) {
      if (!first) sb.append(", ");
      sb.append("cnNameWhole:");
      if (this.cnNameWhole == null) {
        sb.append("null");
      } else {
        sb.append(this.cnNameWhole);
      }
      first = false;
    }
    if (isSetCnNamePartical()) {
      if (!first) sb.append(", ");
      sb.append("cnNamePartical:");
      if (this.cnNamePartical == null) {
        sb.append("null");
      } else {
        sb.append(this.cnNamePartical);
      }
      first = false;
    }
    if (isSetEnv()) {
      if (!first) sb.append(", ");
      sb.append("env:");
      if (this.env == null) {
        sb.append("null");
      } else {
        sb.append(this.env);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ReqBrokerOptionStandardSchemeFactory implements SchemeFactory {
    public ReqBrokerOptionStandardScheme getScheme() {
      return new ReqBrokerOptionStandardScheme();
    }
  }

  private static class ReqBrokerOptionStandardScheme extends StandardScheme<ReqBrokerOption> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ReqBrokerOption struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // BROKER_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.brokerId = iprot.readI32();
              struct.setBrokerIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // ENG_NAME_WHOLE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.engNameWhole = iprot.readString();
              struct.setEngNameWholeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // ENG_NAME_PARTICAL
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.engNamePartical = iprot.readString();
              struct.setEngNameParticalIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // CN_NAME_WHOLE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.cnNameWhole = iprot.readString();
              struct.setCnNameWholeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // CN_NAME_PARTICAL
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.cnNamePartical = iprot.readString();
              struct.setCnNameParticalIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // ENV
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.env = com.longsheng.xueqiao.broker.thriftapi.TechPlatformEnv.findByValue(iprot.readI32());
              struct.setEnvIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ReqBrokerOption struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.isSetBrokerId()) {
        oprot.writeFieldBegin(BROKER_ID_FIELD_DESC);
        oprot.writeI32(struct.brokerId);
        oprot.writeFieldEnd();
      }
      if (struct.engNameWhole != null) {
        if (struct.isSetEngNameWhole()) {
          oprot.writeFieldBegin(ENG_NAME_WHOLE_FIELD_DESC);
          oprot.writeString(struct.engNameWhole);
          oprot.writeFieldEnd();
        }
      }
      if (struct.engNamePartical != null) {
        if (struct.isSetEngNamePartical()) {
          oprot.writeFieldBegin(ENG_NAME_PARTICAL_FIELD_DESC);
          oprot.writeString(struct.engNamePartical);
          oprot.writeFieldEnd();
        }
      }
      if (struct.cnNameWhole != null) {
        if (struct.isSetCnNameWhole()) {
          oprot.writeFieldBegin(CN_NAME_WHOLE_FIELD_DESC);
          oprot.writeString(struct.cnNameWhole);
          oprot.writeFieldEnd();
        }
      }
      if (struct.cnNamePartical != null) {
        if (struct.isSetCnNamePartical()) {
          oprot.writeFieldBegin(CN_NAME_PARTICAL_FIELD_DESC);
          oprot.writeString(struct.cnNamePartical);
          oprot.writeFieldEnd();
        }
      }
      if (struct.env != null) {
        if (struct.isSetEnv()) {
          oprot.writeFieldBegin(ENV_FIELD_DESC);
          oprot.writeI32(struct.env.getValue());
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ReqBrokerOptionTupleSchemeFactory implements SchemeFactory {
    public ReqBrokerOptionTupleScheme getScheme() {
      return new ReqBrokerOptionTupleScheme();
    }
  }

  private static class ReqBrokerOptionTupleScheme extends TupleScheme<ReqBrokerOption> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ReqBrokerOption struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetBrokerId()) {
        optionals.set(0);
      }
      if (struct.isSetEngNameWhole()) {
        optionals.set(1);
      }
      if (struct.isSetEngNamePartical()) {
        optionals.set(2);
      }
      if (struct.isSetCnNameWhole()) {
        optionals.set(3);
      }
      if (struct.isSetCnNamePartical()) {
        optionals.set(4);
      }
      if (struct.isSetEnv()) {
        optionals.set(5);
      }
      oprot.writeBitSet(optionals, 6);
      if (struct.isSetBrokerId()) {
        oprot.writeI32(struct.brokerId);
      }
      if (struct.isSetEngNameWhole()) {
        oprot.writeString(struct.engNameWhole);
      }
      if (struct.isSetEngNamePartical()) {
        oprot.writeString(struct.engNamePartical);
      }
      if (struct.isSetCnNameWhole()) {
        oprot.writeString(struct.cnNameWhole);
      }
      if (struct.isSetCnNamePartical()) {
        oprot.writeString(struct.cnNamePartical);
      }
      if (struct.isSetEnv()) {
        oprot.writeI32(struct.env.getValue());
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ReqBrokerOption struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(6);
      if (incoming.get(0)) {
        struct.brokerId = iprot.readI32();
        struct.setBrokerIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.engNameWhole = iprot.readString();
        struct.setEngNameWholeIsSet(true);
      }
      if (incoming.get(2)) {
        struct.engNamePartical = iprot.readString();
        struct.setEngNameParticalIsSet(true);
      }
      if (incoming.get(3)) {
        struct.cnNameWhole = iprot.readString();
        struct.setCnNameWholeIsSet(true);
      }
      if (incoming.get(4)) {
        struct.cnNamePartical = iprot.readString();
        struct.setCnNameParticalIsSet(true);
      }
      if (incoming.get(5)) {
        struct.env = com.longsheng.xueqiao.broker.thriftapi.TechPlatformEnv.findByValue(iprot.readI32());
        struct.setEnvIsSet(true);
      }
    }
  }

}

