/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package xueqiao.hosting.machine;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class SyncHostingUserPage implements org.apache.thrift.TBase<SyncHostingUserPage, SyncHostingUserPage._Fields>, java.io.Serializable, Cloneable, Comparable<SyncHostingUserPage> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("SyncHostingUserPage");

  private static final org.apache.thrift.protocol.TField TOTAL_NUM_FIELD_DESC = new org.apache.thrift.protocol.TField("totalNum", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField SYNC_HOSTING_USER_LIST_FIELD_DESC = new org.apache.thrift.protocol.TField("syncHostingUserList", org.apache.thrift.protocol.TType.LIST, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new SyncHostingUserPageStandardSchemeFactory());
    schemes.put(TupleScheme.class, new SyncHostingUserPageTupleSchemeFactory());
  }

  public int totalNum; // optional
  public List<SyncHostingUser> syncHostingUserList; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    TOTAL_NUM((short)1, "totalNum"),
    SYNC_HOSTING_USER_LIST((short)2, "syncHostingUserList");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // TOTAL_NUM
          return TOTAL_NUM;
        case 2: // SYNC_HOSTING_USER_LIST
          return SYNC_HOSTING_USER_LIST;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __TOTALNUM_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  private _Fields optionals[] = {_Fields.TOTAL_NUM,_Fields.SYNC_HOSTING_USER_LIST};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.TOTAL_NUM, new org.apache.thrift.meta_data.FieldMetaData("totalNum", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.SYNC_HOSTING_USER_LIST, new org.apache.thrift.meta_data.FieldMetaData("syncHostingUserList", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, SyncHostingUser.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(SyncHostingUserPage.class, metaDataMap);
  }

  public SyncHostingUserPage() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public SyncHostingUserPage(SyncHostingUserPage other) {
    __isset_bitfield = other.__isset_bitfield;
    this.totalNum = other.totalNum;
    if (other.isSetSyncHostingUserList()) {
      List<SyncHostingUser> __this__syncHostingUserList = new ArrayList<SyncHostingUser>(other.syncHostingUserList.size());
      for (SyncHostingUser other_element : other.syncHostingUserList) {
        __this__syncHostingUserList.add(new SyncHostingUser(other_element));
      }
      this.syncHostingUserList = __this__syncHostingUserList;
    }
  }

  public SyncHostingUserPage deepCopy() {
    return new SyncHostingUserPage(this);
  }

  @Override
  public void clear() {
    setTotalNumIsSet(false);
    this.totalNum = 0;
    this.syncHostingUserList = null;
  }

  public int getTotalNum() {
    return this.totalNum;
  }

  public SyncHostingUserPage setTotalNum(int totalNum) {
    this.totalNum = totalNum;
    setTotalNumIsSet(true);
    return this;
  }

  public void unsetTotalNum() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __TOTALNUM_ISSET_ID);
  }

  /** Returns true if field totalNum is set (has been assigned a value) and false otherwise */
  public boolean isSetTotalNum() {
    return EncodingUtils.testBit(__isset_bitfield, __TOTALNUM_ISSET_ID);
  }

  public void setTotalNumIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __TOTALNUM_ISSET_ID, value);
  }

  public int getSyncHostingUserListSize() {
    return (this.syncHostingUserList == null) ? 0 : this.syncHostingUserList.size();
  }

  public java.util.Iterator<SyncHostingUser> getSyncHostingUserListIterator() {
    return (this.syncHostingUserList == null) ? null : this.syncHostingUserList.iterator();
  }

  public void addToSyncHostingUserList(SyncHostingUser elem) {
    if (this.syncHostingUserList == null) {
      this.syncHostingUserList = new ArrayList<SyncHostingUser>();
    }
    this.syncHostingUserList.add(elem);
  }

  public List<SyncHostingUser> getSyncHostingUserList() {
    return this.syncHostingUserList;
  }

  public SyncHostingUserPage setSyncHostingUserList(List<SyncHostingUser> syncHostingUserList) {
    this.syncHostingUserList = syncHostingUserList;
    return this;
  }

  public void unsetSyncHostingUserList() {
    this.syncHostingUserList = null;
  }

  /** Returns true if field syncHostingUserList is set (has been assigned a value) and false otherwise */
  public boolean isSetSyncHostingUserList() {
    return this.syncHostingUserList != null;
  }

  public void setSyncHostingUserListIsSet(boolean value) {
    if (!value) {
      this.syncHostingUserList = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case TOTAL_NUM:
      if (value == null) {
        unsetTotalNum();
      } else {
        setTotalNum((Integer)value);
      }
      break;

    case SYNC_HOSTING_USER_LIST:
      if (value == null) {
        unsetSyncHostingUserList();
      } else {
        setSyncHostingUserList((List<SyncHostingUser>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case TOTAL_NUM:
      return Integer.valueOf(getTotalNum());

    case SYNC_HOSTING_USER_LIST:
      return getSyncHostingUserList();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case TOTAL_NUM:
      return isSetTotalNum();
    case SYNC_HOSTING_USER_LIST:
      return isSetSyncHostingUserList();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof SyncHostingUserPage)
      return this.equals((SyncHostingUserPage)that);
    return false;
  }

  public boolean equals(SyncHostingUserPage that) {
    if (that == null)
      return false;

    boolean this_present_totalNum = true && this.isSetTotalNum();
    boolean that_present_totalNum = true && that.isSetTotalNum();
    if (this_present_totalNum || that_present_totalNum) {
      if (!(this_present_totalNum && that_present_totalNum))
        return false;
      if (this.totalNum != that.totalNum)
        return false;
    }

    boolean this_present_syncHostingUserList = true && this.isSetSyncHostingUserList();
    boolean that_present_syncHostingUserList = true && that.isSetSyncHostingUserList();
    if (this_present_syncHostingUserList || that_present_syncHostingUserList) {
      if (!(this_present_syncHostingUserList && that_present_syncHostingUserList))
        return false;
      if (!this.syncHostingUserList.equals(that.syncHostingUserList))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(SyncHostingUserPage other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetTotalNum()).compareTo(other.isSetTotalNum());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTotalNum()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.totalNum, other.totalNum);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetSyncHostingUserList()).compareTo(other.isSetSyncHostingUserList());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSyncHostingUserList()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.syncHostingUserList, other.syncHostingUserList);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("SyncHostingUserPage(");
    boolean first = true;

    if (isSetTotalNum()) {
      sb.append("totalNum:");
      sb.append(this.totalNum);
      first = false;
    }
    if (isSetSyncHostingUserList()) {
      if (!first) sb.append(", ");
      sb.append("syncHostingUserList:");
      if (this.syncHostingUserList == null) {
        sb.append("null");
      } else {
        sb.append(this.syncHostingUserList);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class SyncHostingUserPageStandardSchemeFactory implements SchemeFactory {
    public SyncHostingUserPageStandardScheme getScheme() {
      return new SyncHostingUserPageStandardScheme();
    }
  }

  private static class SyncHostingUserPageStandardScheme extends StandardScheme<SyncHostingUserPage> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, SyncHostingUserPage struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // TOTAL_NUM
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.totalNum = iprot.readI32();
              struct.setTotalNumIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // SYNC_HOSTING_USER_LIST
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list24 = iprot.readListBegin();
                struct.syncHostingUserList = new ArrayList<SyncHostingUser>(_list24.size);
                for (int _i25 = 0; _i25 < _list24.size; ++_i25)
                {
                  SyncHostingUser _elem26;
                  _elem26 = new SyncHostingUser();
                  _elem26.read(iprot);
                  struct.syncHostingUserList.add(_elem26);
                }
                iprot.readListEnd();
              }
              struct.setSyncHostingUserListIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, SyncHostingUserPage struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.isSetTotalNum()) {
        oprot.writeFieldBegin(TOTAL_NUM_FIELD_DESC);
        oprot.writeI32(struct.totalNum);
        oprot.writeFieldEnd();
      }
      if (struct.syncHostingUserList != null) {
        if (struct.isSetSyncHostingUserList()) {
          oprot.writeFieldBegin(SYNC_HOSTING_USER_LIST_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.syncHostingUserList.size()));
            for (SyncHostingUser _iter27 : struct.syncHostingUserList)
            {
              _iter27.write(oprot);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class SyncHostingUserPageTupleSchemeFactory implements SchemeFactory {
    public SyncHostingUserPageTupleScheme getScheme() {
      return new SyncHostingUserPageTupleScheme();
    }
  }

  private static class SyncHostingUserPageTupleScheme extends TupleScheme<SyncHostingUserPage> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, SyncHostingUserPage struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetTotalNum()) {
        optionals.set(0);
      }
      if (struct.isSetSyncHostingUserList()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetTotalNum()) {
        oprot.writeI32(struct.totalNum);
      }
      if (struct.isSetSyncHostingUserList()) {
        {
          oprot.writeI32(struct.syncHostingUserList.size());
          for (SyncHostingUser _iter28 : struct.syncHostingUserList)
          {
            _iter28.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, SyncHostingUserPage struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.totalNum = iprot.readI32();
        struct.setTotalNumIsSet(true);
      }
      if (incoming.get(1)) {
        {
          org.apache.thrift.protocol.TList _list29 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.syncHostingUserList = new ArrayList<SyncHostingUser>(_list29.size);
          for (int _i30 = 0; _i30 < _list29.size; ++_i30)
          {
            SyncHostingUser _elem31;
            _elem31 = new SyncHostingUser();
            _elem31.read(iprot);
            struct.syncHostingUserList.add(_elem31);
          }
        }
        struct.setSyncHostingUserListIsSet(true);
      }
    }
  }

}

