/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.longsheng.xueqiao.contract.quotation.source.thriftapi;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * 行情账号登录状态信息
 */
public enum LoginState implements org.apache.thrift.TEnum {
  IDLE(0),
  LOGINNED(1),
  PASSWORD_ERROR(2);

  private final int value;

  private LoginState(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static LoginState findByValue(int value) { 
    switch (value) {
      case 0:
        return IDLE;
      case 1:
        return LOGINNED;
      case 2:
        return PASSWORD_ERROR;
      default:
        return null;
    }
  }
}
