/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.longsheng.xueqiao.contract.quotation.source.thriftapi;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum QuotationSourceError implements org.apache.thrift.TEnum {
  COMMODITY_SUBSCRIBE_QUOTA_EXIST(1000),
  COMMODITY_SUBSCRIBE_QUOTA_NOT_FOUND(1001),
  QUOTA_FULL(1002),
  SUBSCRIBE_EXIST(1003),
  ACCOUNT_QUOTA_NOT_FOUND(1004),
  ACCOUNT_EXIST(1005);

  private final int value;

  private QuotationSourceError(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static QuotationSourceError findByValue(int value) { 
    switch (value) {
      case 1000:
        return COMMODITY_SUBSCRIBE_QUOTA_EXIST;
      case 1001:
        return COMMODITY_SUBSCRIBE_QUOTA_NOT_FOUND;
      case 1002:
        return QUOTA_FULL;
      case 1003:
        return SUBSCRIBE_EXIST;
      case 1004:
        return ACCOUNT_QUOTA_NOT_FOUND;
      case 1005:
        return ACCOUNT_EXIST;
      default:
        return null;
    }
  }
}
