/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package xueqiao.mailbox.thriftdata.mb;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * 信息状态
 */
public enum MStatus implements org.apache.thrift.TEnum {
  MS_VALID(0),
  MS_SENDING(1),
  MS_PAUSE(2),
  MS_COMPLETED(10);

  private final int value;

  private MStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static MStatus findByValue(int value) { 
    switch (value) {
      case 0:
        return MS_VALID;
      case 1:
        return MS_SENDING;
      case 2:
        return MS_PAUSE;
      case 10:
        return MS_COMPLETED;
      default:
        return null;
    }
  }
}
