/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.longsheng.xueqiao.contract.thriftapi;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ContractManageErrorCode implements org.apache.thrift.TEnum {
  MAP_FILE_READ_FAIL(2001),
  MAP_FILE_MD5_ERROR(2002),
  DATA_FORMAT_ERROR(2003),
  PLATFORM_COMMODITY_NOT_FOUND(2004),
  PLATFORM_COMMODITY_MORE_THAN_ONE(2005),
  PLATFORM_NOT_SUPPORT(2006),
  PLATFORM_COMMODITY_PROPERTY_ERROR(2007),
  SLED_COMMODITY_NO_DELETE(2008),
  SLED_COMMODITY_WORKING_STATUS_ERROR(2009);

  private final int value;

  private ContractManageErrorCode(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ContractManageErrorCode findByValue(int value) { 
    switch (value) {
      case 2001:
        return MAP_FILE_READ_FAIL;
      case 2002:
        return MAP_FILE_MD5_ERROR;
      case 2003:
        return DATA_FORMAT_ERROR;
      case 2004:
        return PLATFORM_COMMODITY_NOT_FOUND;
      case 2005:
        return PLATFORM_COMMODITY_MORE_THAN_ONE;
      case 2006:
        return PLATFORM_NOT_SUPPORT;
      case 2007:
        return PLATFORM_COMMODITY_PROPERTY_ERROR;
      case 2008:
        return SLED_COMMODITY_NO_DELETE;
      case 2009:
        return SLED_COMMODITY_WORKING_STATUS_ERROR;
      default:
        return null;
    }
  }
}
