/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.longsheng.xueqiao.payment.product.thriftapi;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * 雪橇平台支持的支付币种
 */
public enum CurrencyType implements org.apache.thrift.TEnum {
  XCOIN(0),
  RMB(1);

  private final int value;

  private CurrencyType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static CurrencyType findByValue(int value) { 
    switch (value) {
      case 0:
        return XCOIN;
      case 1:
        return RMB;
      default:
        return null;
    }
  }
}
