/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.longsheng.xueqiao.payment.product.thriftapi;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ProductPurpose implements org.apache.thrift.TEnum {
  NEW(0),
  UPGRADE(1),
  RECHARGE_XCOIN(2),
  RECHARGE_TIME(3),
  PERSONAL_NEW(4),
  PERSONAL_RECHARGE_TIME(5);

  private final int value;

  private ProductPurpose(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ProductPurpose findByValue(int value) { 
    switch (value) {
      case 0:
        return NEW;
      case 1:
        return UPGRADE;
      case 2:
        return RECHARGE_XCOIN;
      case 3:
        return RECHARGE_TIME;
      case 4:
        return PERSONAL_NEW;
      case 5:
        return PERSONAL_RECHARGE_TIME;
      default:
        return null;
    }
  }
}
